version = 1

test_patterns = [
  "api.Tests/**",
  "app/__tests__/**",
  "app/components/__tests__/**"
]

[[analyzers]]
name = "csharp"

[[analyzers]]
name = "go"

  [analyzers.meta]
  import_root = "github.com/kromby/Ez.Ord"